# Generated by Django 3.1.7 on 2021-03-29 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restaurant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20, verbose_name='Country')),
                ('street', models.CharField(max_length=30, verbose_name='Street')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='ZIP')),
                ('website', models.CharField(blank=True, max_length=70)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('opening_hours', models.CharField(max_length=13)),
                ('image', models.ImageField(blank=True, null=True, upload_to=restaurant.models.user_directory_path)),
                ('price_level', models.CharField(choices=[('0', 'No information'), ('1', 'Budget'), ('2', 'Fair'), ('3', 'Expensive')], default='0', max_length=2)),
                ('categories', models.CharField(choices=[('0', 'No category'), ('1', 'Pub'), ('2', 'Italian'), ('3', 'Fast Food'), ('4', 'Chinese'), ('5', 'Thai'), ('6', 'Oriental'), ('7', 'Vegetarian'), ('8', 'Bar'), ('9', 'Sea Food')], default='0', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
