# Generated by Django 3.1.7 on 2021-03-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20210331_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='categories',
            field=models.CharField(choices=[('No category', '0'), ('Pub', '1'), ('Italian', '2'), ('Fast Food', '3'), ('Chinese', '4'), ('Thai', '5'), ('Oriental', '6'), ('Vegetarian', '7'), ('Bar', '8'), ('Sea Food', '9')], default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_level',
            field=models.CharField(choices=[('No information', '0'), ('Budget', '1'), ('Fair', '2'), ('Expensive', '3')], default='0', max_length=15),
        ),
    ]
