# Generated by Django 3.1.7 on 2021-03-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('0', 'no rating'), ('1', 'one star'), ('2', 'two stars'), ('3', 'three stars'), ('4', 'four stars'), ('5', 'five stars')], verbose_name='review rating'),
        ),
    ]
